---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../defaults/template_info.yml"
    - "{{ playbook_dir }}/../../defaults/secrets.yml"

  pre_tasks:
    - name: Ensure 'terraform.tfvars' template is deployed
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../templates/terraform.tfvars.j2"
        dest: "{{ playbook_dir }}/../../../terraform/terraform.tfvars"

  tasks:
    - name: Ensure infrastructure is destroyed with terraform
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../../terraform/"
        variables_files: "{{ playbook_dir }}/../../../terraform/terraform.tfvars"
        state: absent

    - name: Ensure local ssh keys are destroyed
      ansible.builtin.file:
        path: "{{ sshkey_folder }}/{{ item }}-{{ project_name }}"
        state: absent
      with_items:
        - "{{ root_username }}"

  post_tasks:
    - name: Remove 'terraform.tfvars' file
      ansible.builtin.file:
        path: "{{ playbook_dir }}/../../../terraform/terraform.tfvars"
        state: absent
