---
- hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../defaults/template_info.yml"
    - "{{ playbook_dir }}/../../defaults/secrets.yml"

  tasks:
    - name: Ensure 'terraform.tfvars' template is deployed
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../templates/terraform.tfvars.j2"
        dest: "{{ playbook_dir }}/../../../terraform/terraform.tfvars"